"""
Django settings for antivirus_s3 project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Cambiar por una clave segura
SECRET_KEY = 'django-insecure-xwt5%sa(z6y7*qf^*)!4372)l)+@=$%xt6e@i35w)m@d=$@gy='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Cambiar a False en producción

ALLOWED_HOSTS = []  # Cambiar por los hosts permitidos en producción


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Gestión de administración
    'django.contrib.auth',  # Gestionar autenticación
    'django.contrib.contenttypes',  # Gestionar contenido
    'django.contrib.sessions',  # Gestionar sessiones
    'django.contrib.messages',  # Gestionar mensajes
    'django.contrib.staticfiles',  # Gestionar archivos estáticos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Gestionar seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',  # Gestionar sessiones
    'django.middleware.common.CommonMiddleware',  # Gestión de middleware
    'django.middleware.csrf.CsrfViewMiddleware',  # Gestionar CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Gestionar autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Gestionar mensajes
    # Gestionar opciones de frame
    # Gestionar opciones de frame
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'antivirus_s3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['src'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'antivirus_s3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {  # Configuración de la base de datos
    'default': {  # Configuración por defecto
        'ENGINE': 'django.db.backends.sqlite3',  # Motor de base de datos
        'NAME': BASE_DIR / 'db.sqlite3',  # Nombre de la base de datos
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
