# Generated by Django 4.2.14 on 2024-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanRecord",
            fields=[
                ("filename", models.CharField(max_length=255)),
                ("bucket_name", models.CharField(max_length=255)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("scan_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_size", models.PositiveIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("request_by", models.CharField(max_length=100)),
            ],
        ),
    ]
